lib/helix_gym_web/router.ex
defmodule HelixGymWeb.Router do
  use HelixGymWeb, :router

  import HelixGymWeb.AdmAuth

  import HelixGymWeb.EmployeeAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HelixGymWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_adm
    plug :fetch_current_employee
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelixGymWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelixGymWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HelixGymWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", HelixGymWeb do
    pipe_through [:browser, :redirect_if_employee_is_authenticated]

    get "/employees/register", EmployeeRegistrationController, :new
    post "/employees/register", EmployeeRegistrationController, :create
    get "/employees/log_in", EmployeeSessionController, :new
    post "/employees/log_in", EmployeeSessionController, :create
    get "/employees/reset_password", EmployeeResetPasswordController, :new
    post "/employees/reset_password", EmployeeResetPasswordController, :create
    get "/employees/reset_password/:token", EmployeeResetPasswordController, :edit
    put "/employees/reset_password/:token", EmployeeResetPasswordController, :update
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser, :require_authenticated_employee]

    # aqui pags funcionarios

    get "/employees/settings", EmployeeSettingsController, :edit
    put "/employees/settings", EmployeeSettingsController, :update
    get "/employees/settings/confirm_email/:token", EmployeeSettingsController, :confirm_email

    get "/adm/register", AdmRegistrationController, :new
    post "/adm/register", AdmRegistrationController, :create
    get "/adm/log_in", AdmSessionController, :new
    post "/adm/log_in", AdmSessionController, :create
    delete "/adm/log_out", AdmSessionController, :delete

    live "/employeepage", EmployeeLive
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser]

    delete "/employees/log_out", EmployeeSessionController, :delete
    get "/employees/confirm", EmployeeConfirmationController, :new
    post "/employees/confirm", EmployeeConfirmationController, :create
    get "/employees/confirm/:token", EmployeeConfirmationController, :confirm
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser, :require_authenticated_adm]

    live "/admmode", AdmLive
    # aqui pags adm
  end
end

lib/helix_gym_web/views/layout_view.ex
defmodule HelixGymWeb.LayoutView do
  use HelixGymWeb, :view
end

lib/helix_gym_web/templates/layout/_adm_menu.html.eex
<ul>
<%= if @current_adm do %>
  <li><%= @current_adm.email %></li>
  <li>Logou</li>
<% else %>
  <li><%= link "Register", to: Routes.adm_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.adm_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/helix_gym_web/templates/layout/_employee_menu.html.eex
<ul>
  <%= cond do %>
    <% @current_employee -> %>
      <li> Hello, <%= @current_employee.name %> </li>
      <li><%= link "Home", to: Routes.live_path(@conn, HelixGymWeb.EmployeeLive) %></li>
      <li><%= link "Settings", to: Routes.employee_settings_path(@conn, :edit) %></li>
      <li><%= link "ADM Mode", to: Routes.adm_session_path(@conn, :new) %></li>
      <li><%= link "Log out", to: Routes.employee_session_path(@conn, :delete), method: :delete %></li>

    <% @current_adm -> %>
      <li>ADM Mode is ON</li>
      <li><%= link "Home", to: Routes.live_path(@conn, HelixGymWeb.AdmLive) %></li>
      <li><%= link "Employee Mode", to: Routes.adm_session_path(@conn, :delete), method: :delete %></li>
      <li><%= link "Log out", to: Routes.employee_session_path(@conn, :delete), method: :delete %></li>

    <% true -> %>
      <li><%= link "Home", to: Routes.page_path(@conn, :index) %></li>
      <li><%= link "Register", to: Routes.employee_registration_path(@conn, :new) %></li>
      <li><%= link "Log in", to: Routes.employee_session_path(@conn, :new) %></li>
  <% end %>
</ul>

lib/helix_gym_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/helix_gym_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/helix_gym_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Pitbull Thay GYM", suffix: " · Helix" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= render "_employee_menu.html", assigns %>
        </nav>
        <h1>Pitbull Thay GYM</h1>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>