lib/helix_gym_web/router.ex
defmodule HelixGymWeb.Router do
  use HelixGymWeb, :router

  import HelixGymWeb.AdmAuth

  import HelixGymWeb.EmployeeAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HelixGymWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_adm
    plug :fetch_current_employee
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelixGymWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelixGymWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HelixGymWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", HelixGymWeb do
    pipe_through [:browser, :redirect_if_employee_is_authenticated]

    get "/employees/register", EmployeeRegistrationController, :new
    post "/employees/register", EmployeeRegistrationController, :create
    get "/employees/log_in", EmployeeSessionController, :new
    post "/employees/log_in", EmployeeSessionController, :create
    get "/employees/reset_password", EmployeeResetPasswordController, :new
    post "/employees/reset_password", EmployeeResetPasswordController, :create
    get "/employees/reset_password/:token", EmployeeResetPasswordController, :edit
    put "/employees/reset_password/:token", EmployeeResetPasswordController, :update
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser, :require_authenticated_employee]

    # aqui pags funcionarios

    get "/employees/settings", EmployeeSettingsController, :edit
    put "/employees/settings", EmployeeSettingsController, :update
    get "/employees/settings/confirm_email/:token", EmployeeSettingsController, :confirm_email

    get "/adm/register", AdmRegistrationController, :new
    post "/adm/register", AdmRegistrationController, :create
    get "/adm/log_in", AdmSessionController, :new
    post "/adm/log_in", AdmSessionController, :create
    delete "/adm/log_out", AdmSessionController, :delete

    live "/employeepage", EmployeeLive
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser]

    delete "/employees/log_out", EmployeeSessionController, :delete
    get "/employees/confirm", EmployeeConfirmationController, :new
    post "/employees/confirm", EmployeeConfirmationController, :create
    get "/employees/confirm/:token", EmployeeConfirmationController, :confirm
  end

  scope "/", HelixGymWeb do
    pipe_through [:browser, :require_authenticated_adm]

    live "/admmode", AdmLive
    # aqui pags adm
  end
end

lib/helix_gym_web/controllers/employee_reset_password_controller.ex
defmodule HelixGymWeb.EmployeeResetPasswordController do
  use HelixGymWeb, :controller

  alias HelixGym.Accounts

  plug :get_employee_by_reset_password_token when action in [:edit, :update]

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"employee" => %{"email" => email}}) do
    if employee = Accounts.get_employee_by_email(email) do
      Accounts.deliver_employee_reset_password_instructions(
        employee,
        &Routes.employee_reset_password_url(conn, :edit, &1)
      )
    end

    # Regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end

  def edit(conn, _params) do
    render(conn, "edit.html", changeset: Accounts.change_employee_password(conn.assigns.employee))
  end

  # Do not log in the employee after reset password to avoid a
  # leaked token giving the employee access to the account.
  def update(conn, %{"employee" => employee_params}) do
    case Accounts.reset_employee_password(conn.assigns.employee, employee_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Password reset successfully.")
        |> redirect(to: Routes.employee_session_path(conn, :new))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  defp get_employee_by_reset_password_token(conn, _opts) do
    %{"token" => token} = conn.params

    if employee = Accounts.get_employee_by_reset_password_token(token) do
      conn |> assign(:employee, employee) |> assign(:token, token)
    else
      conn
      |> put_flash(:error, "Reset password link is invalid or it has expired.")
      |> redirect(to: "/")
      |> halt()
    end
  end
end

lib/helix_gym_web/views/employee_reset_password_view.ex
defmodule HelixGymWeb.EmployeeResetPasswordView do
  use HelixGymWeb, :view
end

lib/helix_gym_web/templates/employee_reset_password/edit.html.eex
<h1>Reset password</h1>

<%= form_for @changeset, Routes.employee_reset_password_path(@conn, :update, @token), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :password, "New password" %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>

  <%= label f, :password_confirmation, "Confirm new password" %>
  <%= password_input f, :password_confirmation, required: true %>
  <%= error_tag f, :password_confirmation %>

  <div>
    <%= submit "Reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.employee_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.employee_session_path(@conn, :new) %>
</p>

lib/helix_gym_web/templates/employee_reset_password/new.html.eex
<h1>Forgot your password?</h1>

<%= form_for :employee, Routes.employee_reset_password_path(@conn, :create), fn f -> %>
  <%= label f, :email %>
  <%= email_input f, :email, required: true %>

  <div>
    <%= submit "Send instructions to reset password" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.employee_registration_path(@conn, :new) %> |
  <%= link "Log in", to: Routes.employee_session_path(@conn, :new) %>
</p>